code: "openHub"
version: "1.1"
title: "Open HUB"
oneliner: "Open source HUB website"
lastUpdate: "2020-03-12"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
