code: "journey"
version: "1.1"
title: "Journey"
oneliner: "Provide functions to search and track startup & individual activities recorded in this system"
lastUpdate: "2020-03-12"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
