code: "interest"
version: "1.1"
title: "Interest"
oneliner: "Manage members interest to provide recommendation"
lastUpdate: "2020-18-12"
developer:
  author: "Rosaan Ramasamy"
  organization: "MaGIC"
  email: "rosaan@mymagic.my"