name: PHP Composer

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./protected
      run:
        composer install -q --no-interaction --no-ansi --no-scripts --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
